"""Add Is Verfied  Field to User Model to show Vervied user  in sytem  

Revision ID: 762a6bb9e46e
Revises: f7d3992f3101
Create Date: 2026-04-29 21:59:29.538085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762a6bb9e46e'
down_revision = 'f7d3992f3101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verivied', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_verivied')

    # ### end Alembic commands ###
