"""Add Is Admin Field to User Model to show user roles in sytem  

Revision ID: f7d3992f3101
Revises: 2fb1af24b426
Create Date: 2026-04-29 21:18:11.392408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d3992f3101'
down_revision = '2fb1af24b426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productimage', schema=None) as batch_op:
        batch_op.alter_column('productline_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('productimage', schema=None) as batch_op:
        batch_op.alter_column('productline_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
